#!/bin/sh
# Vérifie si on doit ignorer les hooks (via la variable d'environnement SKIP_GIT_HOOKS ou le paramètre --no-verify)
if [ -n "$SKIP_GIT_HOOKS" ]; then
    exit 0
fi

# Récupère le chemin des hooks configuré et exécute le script PowerShell
HOOKS_PATH=$(git config --get core.hooksPath)

# Exécute le script PowerShell
pwsh -ExecutionPolicy Bypass -NoProfile -File "${HOOKS_PATH}\\scripts\\commit-msg.ps1" -CommitMessageFile "$1"
